# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OKHouseCheck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OKHouseCheck
   pod 'AlamofireImage', '~> 3.1'
   # pod 'SlideMenuControllerSwift'
   pod 'XCGLogger', '~> 4.0.0'
   pod 'DatePickerDialog'
end
